# Generated by Django 2.2 on 2019-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190423_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts/%Y/%m/%d'),
        ),
    ]
