# Generated by Django 2.2.1 on 2019-05-11 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name=datetime.datetime(2019, 5, 11, 18, 50, 16, 357113, tzinfo=utc)),
        ),
    ]
